config/routes.rb
Rails.application.routes.draw do
  root 'playlists#index'
  resources :playlists

  get 'oauth' => 'playlists#oauth'
  get 'reset' => 'playlists#reset'
  get 'delete_user_playlists' => 'playlists#delete_user_playlists'
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
end

app/models/yt_api.rb
require 'rubygems'
require 'yt'

class YtApi

  def initialize
    configure
    if Rails.env.development?
      @redirect_uri = 'http://localhost:3000/oauth'
    else
      @redirect_uri = 'https://pure-retreat-81398.herokuapp.com/oauth'
    end
  end

  def authentication_url
    scopes = ['youtube', 'youtube.readonly', 'userinfo.email']
    Yt::Account.new(scopes: scopes, redirect_uri: @redirect_uri).authentication_url
  end

  def create_playlist(name, url, auth)
    channel = create_channel(url)
    name = channel.title
    vid_ids = channel.videos.where(order: 'viewCount').map { |v| v.id }[0..9]
    create_account(auth)
    playlist = @account.create_playlist(title: name, privacy_status: "public")
    vid_ids.each { |id| playlist.add_video(id) }
    playlist_url_from_id(playlist.id)
  end

  def playlist_url_from_id(id)
    "https://www.youtube.com/playlist?list=#{id}"
  end

  def get_last_playlist
    @account.playlists.first if @account
  end

  def delete_all_playlists(auth)
    account = create_account(auth)
    account.playlists.each do |playlist|
      playlist.delete unless playlist.title == "Liked Videos" || playlist.title == "Favorites"
    end
    true
  end

  def channel_name(url)
    create_channel(url).title
  end

  def create_channel(url)
    Yt::Channel.new url: url
  end

  def create_account(auth_code)
    @account = Yt::Account.new authorization_code: auth_code, redirect_uri: @redirect_uri
  end

  def get_popular_vids(url)
    create_channel(url).videos.where(order: 'viewCount')
  end

  def configure
    Yt.configure do |config|
      config.client_id = ENV['CLIENT_ID']
      config.client_secret = ENV['CLIENT_SECRET']
      config.api_key = ENV['KEY']
      config.log_level = :debug
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController

  include PlaylistsHelper

  def new
    @playlist = Playlist.new
    if session[:oauth] != session[:lastauth] || session[:oauth].nil?
     render :new
    else
      render :oauth
    end
  end

  # NOTE: URL's must be in http:// format
  def create
    @playlist = Playlist.new(whitelisted_playlist_params)
    @playlist.popular_url = gen_pop_url(@playlist.url)
    @playlist.playlistID = id_from_url(@playlist.popular_url)
    @playlist.channelname = gen_channel_name(@playlist.url)
    session[:lastauth] = session[:oauth]
    if @playlist.save
      redirect_to playlist_path(@playlist)
    else
      render :new
    end
  end

  def show
    @playlist = Playlist.find(params[:id])
  end

  def index
    @playlists = Playlist.all
    @last_id = @playlists.last.playlistID if @playlists.any?
  end

  def edit
    @playlist = Playlist.find(params[:id])
  end

  def update
    @playlist = Playlist.find(params[:id])
    if @playlist.update(whitelisted_playlist_params)
      redirect_to playlist_path(@playlist)
    else
      flash.now[:alert] = "That's not valid input"
      render :edit
    end
  end

  def oauth
    session[:oauth] = params[:code]
    redirect_to new_playlist_path
  end

  def reset
    reset_session
    redirect_to new_playlist_path
  end

  def delete_user_playlists
    delete_all_user_playlists
    redirect_to playlists_path
  end

  private

  def whitelisted_playlist_params
    params.require(:playlist).permit(:url, :channelname, :playlistID)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
  def auth_url
    YtApi.new.authentication_url
  end

  def gen_pop_url(url)
    YtApi.new.create_playlist('name', url, session[:oauth])
  end

  def gen_channel_name(url)
    YtApi.new.channel_name(url)
  end

  def id_from_url(url)
    regex = /[=](.*)/
    url.match(regex)[0][1..-1]
  end

  def delete_all_user_playlists
    YtApi.new.delete_all_playlists(session[:oauth])
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjectHackaYtPlaylist</title>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="row header">
    <%= button_to "All Playlists", playlists_path, :class => "col-xs-2 col-xs-offset-1 btn btn-primary", :method => :get %>
    <%= button_to "Create a new Playlist", new_playlist_path, :class => "col-xs-2 col-xs-offset-2 btn btn-success", :method => :get %>
    <%= button_to "New Auth Token", auth_url, :class => "col-xs-2 col-xs-offset-2 btn btn-danger" %>
    <hr>
  </header>
  <div id="wrap">
    <div id="main" class="container clear-top">
      <div class="row">
        <div class="span12">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
  <footer class="footer">
    <hr>
    <a class="personal-website col-xs-offset-3 " href="http://www.morganmart.in">Morgan Martin</a>
    <%= link_to "Delete all (your) playlists", delete_user_playlists_path %>
  </footer>
</body>
</html>

app/views/playlists/_form.html.erb
<%= form_for @playlist do |p| %>
  <%= p.label :'Channel URL' %>
  <%= p.text_field :url %>

  <%= p.submit %>
<% end %>

app/views/playlists/edit.html.erb
<%= form_for @playlist do |p| %>
  <%= p.label :'Playlist Name' %>
  <%= p.text_field :channelname %>

  <%= p.label :'Playlist ID' %>
  <%= p.text_field :playlistID %>

  <%= p.submit %>
<% end %>

app/views/playlists/index.html.erb
<p class="greeting">Welcome to the community youtube playlist! This is a collection of
  youtube playlists by the community for the community!</p>
<p class="greeting">How it works:
  You supply a youtube channel link and we create a playlist out of
  that channel's ten most popular videos. This is really handy for
  music playlists!
  The process uses oAuth meaning that the playlist will be created
  under your youtube channel. It is public by default and will be
  listed here for others to enjoy!</p>
</p>
<ul>
  <% @playlists.each do |p| %>
    <li class="col-xs-offset-4">
      <%= link_to p.channelname, playlist_url(p) %>
      <%= '|' %>
      <%= link_to "Playlist", p.popular_url %>
      <%= '|' %>
      <%= link_to "Edit", edit_playlist_path(p.id) %>
    </li>
<% end %>
</ul>
<iframe class="col-xs-offset-3" id="ytplayer" type="text/html" width="640" height="390"
        src='https://www.youtube.com/embed?listType=playlist&list=<%= @last_id %>'
        frameborder="0"></iframe>

app/views/playlists/new.html.erb
<h1>Input the channel for which you would like to generate a playlist</h1>
<h2>NOTE: URL must be in "http://www.youryoutubechannelhere.com" format, or it won't work!</h2>
<%= render 'form' %>

app/views/playlists/oauth.html.erb
<h3 class="col-xs-offset-3">Select authorize to authorize with oauth</h3>
<p class="col-xs-offset-5"><a href='<%= auth_url %>'>AUTHORIZE</a>

app/views/playlists/show.html.erb
<div class="row">
  <iframe class="col-xs-8 col-xs-offset-3" id="ytplayer" type="text/html" width="640" height="390"
          src='https://www.youtube.com/embed?listType=playlist&list=<%= @playlist.playlistID %>'
          frameborder="0"></iframe>
</div>

<div class="row">
  <a class="col-xs-2 col-xs-offset-4" href='<%= @playlist.url %>'><%= @playlist.channelname %> URL</a>
  <a class="col-xs-2 col-xs-offset-2" href='<%= @playlist.popular_url %>'>Playlist URL</a>
</div>